
menu:
  home: /
  about: /about-me/
  blog: /archives/
  projects: projects

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-11

# Copyright Infomation
startyear: 2017
